server:
  port: 8091

sics:
  life:
    #生产
    xmlServerAdd: http://10.0.11.111:9090/SicsServerQHR/SicsWSServlet
    #测试
    testXmlServerAdd: http://10.0.51.111:9080/SicsServer/SicsWSServlet

spring:
  application:
    name: "sxt-serv"
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    dynamic:
      #数据源
      primary: local
      strict: false
      datasource:
        local:
          url: jdbc:oracle:thin:@localhost:1521:orcl
          username: ROOT
          password: root
        #HA_DATA_UAT:
        #  url: jdbc:oracle:thin:@172.19.50.66:1521/test02db
        #  username: SICSLIFECEDED_DEBUG1
        #  password: SICSLIFECEDED_DEBUG1

mybatis-plus:
  type-aliases-package: com.sics.sxt.pojo.*
    #开启sql显示
    #configuration:
    #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true

